
#-------------- FIND PGSQL_INCLUDE_DIR ------------------
FIND_PATH(PGSQL_INCLUDE_DIR pg_config.h
		$ENV{PGSQL_INCLUDE_DIR}
		$ENV{PGSQL_DIR}/include
		/usr/include/postgresql/
)

#----------------- FIND PGSQL_LIB_DIR -------------------
	FIND_LIBRARY(PGSQL_LIB NAMES pq
				 PATHS
				 $ENV{PGSQL_DIR}/lib
				 /usr/lib
)

IF(PGSQL_LIB)
	GET_FILENAME_COMPONENT(PGSQL_LIB_DIR ${PGSQL_LIB} PATH)
ENDIF(PGSQL_LIB)

IF (PGSQL_INCLUDE_DIR AND PGSQL_LIB_DIR)
	SET(PGSQL_FOUND TRUE)

	INCLUDE_DIRECTORIES(${PGSQL_INCLUDE_DIR})
	LINK_DIRECTORIES(${PGSQL_LIB_DIR})

	SET(PGSQL_CLIENT_LIBS pq)


	MESSAGE(STATUS "PostgresSQL Include dir: ${PGSQL_INCLUDE_DIR}  library dir: ${PGSQL_LIB_DIR}")
	MESSAGE(STATUS "PostgresSQL client libraries: ${PGSQL_CLIENT_LIBS}")
ELSE (PGSQL_INCLUDE_DIR AND PGSQL_LIB_DIR)
	MESSAGE(FATAL_ERROR "Cannot find PostgresSQL. Include dir: ${PGSQL_INCLUDE_DIR}  library dir: ${PGSQL_LIB_DIR}")
ENDIF (PGSQL_INCLUDE_DIR AND PGSQL_LIB_DIR)

